### ISSUE TITLE
config.payUrl should injectable

### ISSUE THREAD

**Issue by AnnatarHe** [nebulasio/nebPay#1]
`config.payUrl` 是写死的。需要针对不同环境进行不同配置。比如 testnet 用 testnet 的 url.

由于我不清楚 testnet 的 url，提不了 pr，麻烦你们尽快解决一下吧。谢了。

**Comment by yupnano** [comment]
谢谢反馈！我们会尽快支持选择 mainnet/testnet，目前配置里的payUrl是测试网的。

**Comment by yupnano** [comment]
目前可以通过callback参数指定主网/测试网. 
https://github.com/nebulasio/nebPay#usage

**Comment by yupnano** [comment]
queryPayInfo是用来查询交易结果的，不是用来得到URL的呀。你可以通过callback参数指定主网的URL，不指定就默认是测试网的。

**Comment by AnnatarHe** [comment]
目前我是这个逻辑。

1. call 合约中的一个方法，得到一个 serialNumber,
2. 随后根据这个 number 调用 queryPayInfo 获得合约返回的内容。

逻辑是这样的吧？

如果不是应该是怎么样的呢？

**Comment by yupnano** [comment]
要得到合约返回的内容还是使用simulateCall 吧，这个直接指定listener来处理返回结果，不能用queryPayInfo来查询。
这个接口其实不属于发送交易，所以打算从nebpay中删掉，文档中已经没有介绍了，不过还可以使用。

**Comment by AnnatarHe** [comment]
看命名似乎是“模拟调用”？那么在主网中可以使用吗？

**Comment by yupnano** [comment]
主网可以用的。
还是需要 强调一下，NebPay与网络无关，它不关心具体使用哪个网络，NebPay只是提供了一个支付接口，只是将交易信息发给钱包，由钱包决定将交易发到哪个网络。

**Comment by yupnano** [comment]
因为`simulateCall `不是发起交易，所以不会弹出交易窗口。只是在后台执行就可以了，主要用来执行合约的查询函数，比如查询账户余额之类的。
返回的`result：null` 说明这个函数调用没有错误，是正常的。

**Comment by daffy6537** [comment]
@AnnatarHe 我也是，你怎么解决的？

**Comment by AnnatarHe** [comment]
@daffy6537 使用 `simulateCall` 就可以了。不过我现在碰到的问题是老告诉我`余额不足`，然而测试网络下，个人账户，合约账户都有余额。

后来。。。我也懒得搞了。
