### ISSUE TITLE
这个设计想法好奇怪...

### ISSUE THREAD

**Issue by qazujmko** [nebulasio/nebPay#11]
1.无法获知用户钱包，无法实现“登录”
2.网络不可以手动选择，那意味着在生产环境只能用主网

**Comment by yupnano** [comment]
Nebpay只是为了给不同平台提供统一的支付接口，所以只解决支付问题。

关于网络选择，nebpay与具体网络无关，因为nebpay不执行具体的交易发送，只是把交易数据发给钱包APP，由APP决定将交易发到主网还是测试网甚至是本地私有网络。

关于获取用户钱包地址，APP不能直接返回用户的钱包信息（就算能实现，APP间的跳转操作也是很不友好的），所以这不是nebpay考虑的内容。浏览器插件和dapp之间可以实现很方便的消息发送，可以另外设计一个接口供浏览器插件使用，这个我们正在考虑实现。

**Comment by qazujmko** [comment]
那移动网页怎么办呢

**Comment by yupnano** [comment]
对了，通过浏览器插件获取用户钱包可以临时使用 [`postMessage`](https://github.com/ChengOrangeJu/WebExtensionWallet/blob/master/example/TestPage_old.html) 的方式，后面我们应该会有更便于使用的接口。
至于移动端，先让用户自己粘贴钱包地址吧，我们会考虑是否有更好的方式。
