### ISSUE TITLE
simulateCall and call were canceled by no reason

### ISSUE THREAD

**Issue by YangLuYang** [nebulasio/nebPay#12]
![image](https://user-images.githubusercontent.com/17721603/39890132-7557286e-54cc-11e8-98b8-049ef55cd3c2.png)
点击这两个按钮后，Chrome控制台的Network TAB显示
![image](https://user-images.githubusercontent.com/17721603/39890218-b7d22a40-54cc-11e8-9bed-f7bf6d203d13.png)

**Comment by yupnano** [comment]
这是跳转app的请求，因为你是用的PC，所以会报错，可以忽略。
另外这个消息里面有两个错误：
* callback 参数是错的，需要pull最新代码。
* call 的 `“args“:”[1]"` 格式是错的，应该是`"args“:”[\"1\"]"`

**Comment by YangLuYang** [comment]
@yupnano 出现了新的问题。
使用最新版的nebPay.js，部署到了主网，通过web-wallet测试通过，前端调用代码如下
![image](https://user-images.githubusercontent.com/17721603/39909508-bffbf8be-5525-11e8-8e57-2a6a80b7ad9c.png)
控制台异常信息如下
![image](https://user-images.githubusercontent.com/17721603/39909560-eaf37c18-5525-11e8-89c1-035927500487.png)

**Comment by yupnano** [comment]
错误原因是你在函数内定义了`var to =  to;` , 因为与函数外的`to` 重名, 导致函数内访问不到函数外定义的`to`, 所以函数内的`var to =  to;` 执行后 `to = undefined`. 所以会有"invalid address format"的错误.

另外，如果args为空，直接写`args = ""` 就行.

**Comment by YangLuYang** [comment]
@yupnano 我还有个小问题。之前有个合约部署在测试网没问题，但是无法部署到主网，
报错信息如下
![image](https://user-images.githubusercontent.com/17721603/39911222-3ae05cd0-552d-11e8-8522-c65e7c149e4b.png)

**Comment by yupnano** [comment]
这个是因为出于安全考虑，目前在主网屏蔽了一些关键词。 稍后我们会在测试网做相同的处理，并完善错误返回信息，错误信息里会注明具体是哪个关键字。

**Comment by ChengOrangeJu** [comment]
Thanks @yupnano
