### ISSUE TITLE
How to get caller's pubkey in smartcontract, or from nebPay

### ISSUE THREAD

**Issue by zoowii** [nebulasio/nebPay#13]
I need get user's pubkey to encrypt something and store it in smartcontract. Now I implement it by get user's wallet file and get pubkey from account. If you provide more apis abount getting caller's pubkey, it will be safer.

eg. my dapp which need get user's pubkey is http://zoowii.com/nebmail

**Comment by yupnano** [comment]
you cannot get pubkey except that user import wallet file on your dapp page directly.
but you can try to get user wallet address, please refer to this issue:
https://github.com/ChengOrangeJu/WebExtensionWallet/issues/6
