### ISSUE TITLE
invalid transaction hash

### ISSUE THREAD

**Issue by asebak** [nebulasio/nebPay#2]
I keep getting this error message when I am trying to call my smart contract, any ideas?  When I deployed the smart contract there were no errors, does this happen when there's a bug in the code of your smart contract?

**Comment by yupnano** [comment]
Please provide more info. Such as your code that calling the smart cobtract, or the args you are using in this transaction.

**Comment by asebak** [comment]
It seems to do with the callargs, what's the proper way of passing a json object to it?

**Comment by yupnano** [comment]
The args are in the form of JSON string of the parameters array, such as["arg"] , ["arg1","arg2"].
