### ISSUE TITLE
simulateCall 与call

### ISSUE THREAD

**Issue by qinrongjun** [nebulasio/nebPay#20]
调用simulateCall能够正确调用合约中的函数并返回正确的值，但是使用call掉起钱包插件后函数返回值为空。

**Comment by yupnano** [comment]
是的，call 是发送交易, 并不会返回被调用函数的返回值，所有交易(包括转账/合约部署和调用)都只会返回交易hash。

要想得到交易返回值，只能试用simulateCall来模拟执行(部署或调用合约)，通过返回信息确认无误后再发送交易即可。

simulateCall 对应于 rpc的[call](https://github.com/nebulasio/wiki/blob/master/rpc.md#call)接口，用于模拟执行，获取运行结果和运行错误信息。
交易发送对应rpc的[sendTransaction](https://github.com/nebulasio/wiki/blob/master/rpc_admin.md#sendtransaction)接口，sendTransaction的交易类型有三种: binary(普通转账), call(合约调用), deploy(合约部署).

**Comment by cssmagic** [comment]
@yupnano 
老兄，我能不能在这里悄悄问一声：文档删除 `simulateCall()` 是啥原因啊，不建议使用了吗？ 😭

**Comment by yupnano** [comment]
@cssmagic 是的，因为这个接口只有插件能支持，钱包app是做不到的。并且这也不算是支付接口，而nebpay是用来做支付的。

**Comment by cssmagic** [comment]
@yupnano 
日常简单的 DApp 功能其实用 nebPay 的 `call()`、`simulateCall()`、`queryPayInfo()` 这三个 API 就可以满足了。如果 `simulateCall()` 不能用了，还得另外加载一个 neb.js，有点不划算 😂 

希望有机会参与讨论星云 JS SDK 的未来发展。我的微信号就是 GitHub 用户名，随时可加我，谢谢。

**Comment by cssmagic** [comment]
> 如果 `simulateCall()` 不能用了，还得另外加载一个 neb.js，有点不划算 😂 

我仔细读了 RPC 文档，已实现直连 `user/call` 接口，不用依赖 nebPay 和钱包扩展，也不用依赖 neb.js。

@yupnano 
我现在终于理解为什么 `simulateCall()` 会从 nebPay 里移除了。谢谢。
