### ISSUE TITLE
nebPay not support Nas nano app 

### ISSUE THREAD

**Issue by act262** [nebulasio/nebPay#22]
Environment: Android 8.1 + Nas nano Wallet app
在h5页面中使用nebPay sdk发起一个交易，然后生成二维码，使用App钱包扫描二维码，提示gasPrice不能为0，而且不能手动修改。同样的交易操作，使用Chrome插件是OK的。
查看代码发现nebPay sdk 里面没有设置gasPrice,gasLimit的属性，而且app没有单独提供扫描这类二维码的操作。

**Comment by yupnano** [comment]
目前测试版nas nano的扫码功能还不完善，新版本中会完善该功能。
你可以用手机浏览器打开Dapp，发送交易的时候可以直接跳转nas nano完成支付。
