### ISSUE TITLE
星云链DAPP开发者联盟微信群

### ISSUE THREAD

**Issue by same4869** [nebulasio/nebPay#31]
一直没找到一个开发者群，建了一个，欢迎大家加入讨论NAS星云链DAPP开发相关，互相赞应用，讨论创意

![image](https://user-images.githubusercontent.com/5135064/40345974-d1da0ca0-5dcd-11e8-957a-c458599324ae.png)

**Comment by ChengOrangeJu** [comment]
添加微信nebulasio留言申请加入技术群即可

**Comment by same4869** [comment]
您好，请问nebpay调起app钱包交易是需要集成安卓或者苹果sdk吗？网页版的可以在移动设备的webview吊起来吗，有没有相关文档谢谢




| |
王迅
邮箱：same4869@126.com
|

签名由 网易邮箱大师 定制

在2018年05月24日 07:11，ChengOrangeJu 写道：

添加微信nebulasio留言申请加入技术群即可
