### ISSUE TITLE
If nebPay call throws an error, how to detect ?

### ISSUE THREAD

**Issue by honey93** [nebulasio/nebPay#33]
If my smart contract has a condition on which it throws error like this:
throw new Error("Sorry, You didn't beat the highest score this time !!");

How to get it on frontend using:
nebPay.call(contractAddress, 0, func, args, {
                listener: cbCallDapp
            });

I tried the below method, but it does not work

nebPay.queryPayInfo("txhash")
            .then(function (resp) {
                alert(resp);
            })
            .catch(function (err) {
                alert(err);
            });

**Comment by yupnano** [comment]
You can simulate the transaction to see if there is an error before sending it.
Here is two ways of simulating a transacton:
- with neb.js: using [`neb.api.call()`](https://nebulasio.github.io/neb.js/API.html#call__anchor)
- with nebpay: using [`nebpay.simulateCall()`](https://github.com/nebulasio/nebPay/blob/master/examples/example.html#L91). see https://github.com/nebulasio/nebPay/issues/20 , 

All of the above two methods is using [Nebulas RPC API `Call`](https://github.com/nebulasio/wiki/blob/master/rpc.md#call)

**Comment by honey93** [comment]
nebpay.simulateCall() is only for read operation ?? You mean to say, for error checking I can call simulateCall, and if get success then can neb.api.call ??

**Comment by yupnano** [comment]
No. 
`neb.api.call()` and  `nebpay.simulateCall()` are functionally equivalent and one can be used instead of the other, rather than one after the other.

**Comment by zhanglongchina** [comment]
到底怎么获取error呢

**Comment by honey93** [comment]
I am able to check for error using simulatecall, and then based on response, calling nebpay.call(). Thanks for helping out.

**Comment by daffy6537** [comment]
can  simulateCall get transaction.from ？

**Comment by honey93** [comment]
Yes, In your smart contract function, you need to call Blockchain.transaction.from and return it. It will come
