### ISSUE TITLE
关于 queryPayInfo() 的 options，文档中的这两处是不是相互矛盾？

### ISSUE THREAD

**Issue by cssmagic** [nebulasio/nebPay#39]
nebPay 的文档： https://github.com/nebulasio/nebPay/blob/master/doc/NebPay%E4%BB%8B%E7%BB%8D.md#querypayinfo

第一个说法：

> `options` 对于`queryPayInfo`接口, `options` 主要用来指定交易查询服务器.

这里的意思似乎是说：`options` 中只有 `callback` 有意义，指定 `listener` 无意义。

第二个说法：

> 使用浏览器插件发送交易时，浏览器插件可以直接返回交易结果给Dapp页面，Dapp端可以指定一个`listener`函数来接收并处理交易返回信息。浏览器插件也可以实现将交易结果发送到交易查询服务器。

这里又表示 `listener` 可以拿到交易返回信息。

***

经我自己测试，似乎指定 `listener` 无效，`listener` 函数并不会被调用。

不知道我的理解是否正确，请回复，谢谢！

**Comment by Heasn** [comment]
这里的文档确实写得很不好，感觉文档编写人员并没有表达清楚。

综合我的开发过程来看，其实`callback`与`querypayinfo`的主要应用场景在移动端上支付跳转到星云钱包APP时查询该交易用的。

在PC浏览器上，用`listener`可以得到该交易的信息。注意：在PC浏览器上`nebpay`并不会把交易流水号（serialNumber）上传到查询服务器上，因为可以直接通过`listener`回调得到`txhash`，所以在浏览器上用`options`的`callback`与`querypayinfo`并不会起作用。

而在移动端上，由于跳转到星云钱包APP后网页无法得到交易的信息，所以这个时候`nebpay`才会将交易流水号上传到交易服务器供你查询。

所以你需要做的是，在移动端时，网页通过`options`的`callback`与`nebpay.querypayinfo`来查询交易，而在PC浏览器上，通过`listener`取得`txhash`后通过`nebulas.js` 里的 `getTransactionReceipt` 来查询交易。

以上是我的理解，还是要等官方人员来回答。

**Comment by cssmagic** [comment]
@yupnano 
谢谢，我基本理解了。

`listener` 对我来说挺有用，请不要轻易去掉 😂

**Comment by cssmagic** [comment]
@Heasn 
我的意思是，对于 `queryPayInfo()` 接口来说，在 `options` 中指定 `listener` 无意义（实测确实是这样）；对其它接口来说，`listener` 有意义。

nebPay 确实可以拿到 txHash，然后通过 neb.js 来查询交易详情，这条路没问题。而另一条路也走得通，不依赖 neb.js，只用 nebPay 就可以获取交易详情。方法就是 nebPay 配合 Chrome 钱包扩展向服务器注册流水号，然后再查询（这与配合手机钱包 app 的方式相同）。

我现在走的是第二条路，这样整个 DApp 不需要加载 neb.js，只需要加载 nebPay。（当然这样的缺点就是，DApp 在手机浏览器中基本不能用。所以正确姿势还是同时加载 nebPay 和 neb.js 呀 😂 ）

我基于 nebPay 封闭了一套工具库，很好用，稍后开源出来。

**Comment by cssmagic** [comment]
@yupnano 
再回头看文档，表达确实有问题。我回头有空会更新一下文档。

**Comment by daffy6537** [comment]
为什么call 不直接返回结果呢？绕这么大弯子

**Comment by yupnano** [comment]
@daffy6537 因为发送交易后并不能立即得到交易结果，交易需要由矿工打包后才算成功，这个过程需要一定的时间。
