### ISSUE TITLE
use NebPay.queryPayInfo(serialNum), but  its execute_result not a JSON

### ISSUE THREAD

**Issue by Nodreame** [nebulasio/nebPay#50]
result is:
```
chainId:1
contract_address:""
data:"eyJGdW5jdGlvbiI6ImdldFVzZXJJbmZvIiwiQXJncyI6IltdIn0="
execute_error:""
execute_result:"{"status":true,"data":{"u_address":"n1Q6DPSbLjGVArrJGwrVFfQoXbbEwc7u4Fu","nickname":"wang","sex":1,"email":"","phone":"","wechatId":"","avatar":"","desc":"","createdate":1529809755000,"logindate":1530270630000,"gamelist":[{"g_address":"n1kgQeum4TTLJAsqn7U8"
from:"n1Q6DPSbLjGVArrJGwrVFfQoXbbEwc7u4Fu"
gas_limit:"200000"
gas_price:"1000000"
gas_used:"21181"
hash:"545d3a52beae97beec55caaacd0871535dde3f9a8196269293927cefdde9fd64"
nonce:75
result:null
status:1
timestamp:1530270614
to:"n1vQTC6WnL9NNjY8RcVMCszLaDqDb73TMtc"
type:"call"
value:"0"
```
It looks like it has been truncated，maybe it's length is too long? But when I use Neb, there is no such problem. Is there any solution? Thx!

**Comment by yupnano** [comment]
**Note:** the data length of `execute_result` in transaction receipt  is limited to 255 Bytes, if you want to receive a large return value from you smart-contract, please use api call instead.

And a similar issue: https://github.com/nebulasio/wiki/issues/200#

**Comment by Nodreame** [comment]
Thx, is there no plans to modify the limit of execute_result's length ?
