### ISSUE TITLE
交易查询服务似乎不稳定，nebPay.queryPayInfo() 经常显示交易流水号不存在

### ISSUE THREAD

**Issue by cssmagic** [nebulasio/nebPay#51]
![screen-shot-2018-07-08-at-01 37 04am](https://user-images.githubusercontent.com/1231359/42413403-9899dae4-8251-11e8-9fb4-7a84308899b1.png)

上图是在测试网开发时顺手截的图。主网一样有这个问题，参见下面的评论。

```
payId pVEFCrPdPs15608ImBRdIyZI78bnPzql does not exist
```

```
{"txhash":"6ef5543b8f657ea59c70bd2884f74be104b44c47b2d4cfea34cb32b44c9f2d1c","contract_address":""}
```

查交易流水号查不到，查 TxHash 就没问题。

***

这不是 nebPay 的问题，是交易查询服务器的问题。但我似乎也只能在这里提 issue 了。

不是 nebPay 版本的问题，最新版同样存在。

不是 callback 参数设置错误等原因，不会犯这种低级错误的。

经常出现 “交易流水号不存在” 的问题，概率很高，但没有规律。似乎也不是完全没有规则，往往长时间离开电脑后第一次发交易时比较容易出现这个问题——心理上感觉似乎是这样，但无法证明。

这个问题困扰了很多群友，很影响 DApp 的可用性。希望能够定位并解决此问题，辛苦啦！

**Comment by cssmagic** [comment]
来贴一个主网的截图。

![nebpay](https://user-images.githubusercontent.com/1231359/42489938-7a59ff50-8440-11e8-9cb5-6d60ca8e0192.png)

```
"serialNumber": "7OOT4zrvgIjawP7XwjzMQp1QaQvfkMyn"
```

```
"txhash": "c1eb2955e42f6e5d24f51f0511dd6d29112daf8e62c26a0dbc65ff63c2659fac"
```

**Comment by lychees** [comment]
+1

**Comment by yupnano** [comment]
The NasExtWallet has been updated:

Add feedback message for posting serialNumber to server. If serialNumber is failed to be posted to server, you should not use queryPayInfo(serialNumber) to query transaction results, please use neb.api.getTransactionReceipt instead.

After a transaction is send, there should be an feedback that if the serialNumber is posted to server successfully. Hence an attribute `error` is added to the return value for `listener(serialNumber, result)`. the result is:

   ```         
    {
        "txhash": "ae41d5459fc8db5ffaee5416585e0874d2324d258258b8c59cda789a04934e1a",
        "contract_address": "",
        "error": "{\"timestamp\":1531231627789,\"status\":400,\"error\":\"Bad Request\",\"exception\":\"org.springframework.web.bind.MissingServletRequestParameterException\",\"message\":\"Required String parameter 'payId' is not present\",\"path\":\"/api/pay\"}"
    }
```            
            
If the error is not empty, it means that the `serialNumber` is not posted to the server, then you should not use `nebpay.queryPayInfo`.

**Comment by cssmagic** [comment]
@yupnano 
谢谢对钱包扩展的升级！

也许将来交易查询服务器在大陆设置节点会好一些。
